export const contextCandidates: Readonly<Record<string, readonly string[]>> = {
  'declaration.root': [
    'package name:',
    'module name:',
    'scope name:',
  ],
  'declaration.package': [
    'package name:',
    'module name:',
    'scope name:',
  ],
  'declaration.module': [
    'alias name as type',
    'enum name as type:',
    'struct name:',
    'template name:',
    'fn name:',
    'let name as type = value',
    'scope name:',
  ],
  'declaration.scope': [
    'alias name as type',
    'enum name as type:',
    'struct name:',
    'template name:',
    'fn name:',
    'let name as type = value',
    'scope name:',
  ],
  'fn.body': [
    'param name as type',
    'let name as type = value',
    'self.field = value',
    'return ',
    'return value as type',
    'use c.expr("")',
  ],
  'struct.body': [
    'field name as type',
    'use c.ptr(value)',
    'fn name:',
  ],
  'template.body': [
    'name',
    'name as any',
    'name as template',
    '... as values',
    'field name as type',
    'use c.ptr(value)',
  ],
  'attribute': [
    '@mutable',
    '@public',
    '@private',
    '@inline',
    '@doc("...")',

    '@include("header.h")',
    '@extern',
    '@intrinsic',
    '@define',
    '@expand',
  ],
};
