export const contextCandidates: Readonly<Record<string, readonly string[]>> = {
  'declaration.root': [
    'package name:',
    'module name:',
    'scope name:',
  ],
  'declaration.package': [
    'package name:',
    'module name:',
    'scope name:',
  ],
  'declaration.module': [
    'alias name -> type',
    'enum name -> type:',
    'struct name:',
    'template name:',
    'template name():',
    'mutable template name():',
    'fn name() -> type:',
    'mutable fn name() -> type:',
    'scope name:',
  ],
  'declaration.scope': [
    'alias name -> type',
    'enum name -> type:',
    'struct name:',
    'template name:',
    'template name():',
    'mutable template name():',
    'fn name() -> type:',
    'mutable fn name() -> type:',
    'scope name:',
  ],
  'fn.body': [
    'let name -> type = value',
    'return ',
    'use c.expr("")',
  ],
  'struct.body': [
    'field name -> type',
    'mutable field name -> type',
    'use c.ptr(value)',
    'fn name() -> type:',
    'mutable fn name() -> type:',
  ],
  'template.body': [
    'name',
    'name -> any',
    'name -> template',
    '... -> values',
    'field name -> type',
    'mutable field name -> type',
    'use c.ptr(value)',
  ],
  'attribute': [
    '@public(header)',
    '@public(source)',
    '@public(all)',

    '@include("header.h")',
    '@static',
    '@extern',
    '@abstract',
    '@define',
    '@expand',
  ],
};
